import type { Metadata } from 'next'
import '@/src/styles/globals.scss'
import {AppProps} from "next/app";
import Layout from "@/src/Layout";
import {LanguageProvider} from "@/src/hooks/useTranslation";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

function App({ Component, pageProps }: AppProps) {
    return (
        <LanguageProvider>
            <Layout>
                <Component {...pageProps} />
            </Layout>
        </LanguageProvider>
    );
}

export default App;
