const common = {
    "app.best_seller": "Best sellers",
    "app.products": "Produkty",
    "app.earrings": "Náušnice",
    "app.necklaces": "Náhrdelníky",
    "app.bracelets": "Náramky",
    "app.contact": "Kontakt",
    "app.blog": "Blog",
    "app.cart": "Košík",
    "app.icon.material": "Kvalita materiálu",
    "app.blog.minutes": "min.",
    "app.new_arrivals": "Novinky",
    "app.description.resistance": "description resistance",
    "app.description.material": "description material",
    "app.icon.timelessness": "Nadčasový design",
    "app.description.timelessness": "description care",
    "app.count": "Počet",
    "app.price": "Cena",
    "app.total_price": "Celková cena",
    "app.total_price_without_tax": "Celková cena bez DPH",
    "app.cart.shipping_and_payment": "Doprava a platba",
    "app.contact.email": "Email",
    "app.contact.field_required": "Toto pole je povinné",
    "app.shipping": "Doprava",
    "app.follow_us": "Sledujte nás",
};

export default common;
