name: Tests

on: [push, pull_request]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Run Jest tests
        run: npm test
        env:
          CI: true
